// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://apdogukikekubpfvivdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwZG9ndWtpa2VrdWJwZnZpdmRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4NDIyODksImV4cCI6MjA4NzQxODI4OX0.hYxhI84KdWX9CfkIf77cDFNpaPePHc8EI5LDMhQGr9M";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);